# ============================
# 房间配置
# ============================
# 需要监听的房间号
room_id = 27163300
# 正在运行VRC的电脑本地LAN ip 和 端口
LAN_ip = "127.0.0.1"
LAN_port = 9000

# ============================
# 事件类型设置
# 默认为排队事件，每秒只能触发一个，多余的进入队列
# fx 应从 Anystate 根据 event_id 触发对应动画，动画由 event_num 控制，长度为 1 秒
# osc每秒汇报排队最前的事件，无事件则汇报(0,0)
# ============================
# 0 = 不监听  
# 1 = 发送至聊天框
# 2 = 更新参数 event_id (int), event_num (float)
# 3 = 前两者都做
[events]
enter    = 1  # 监听进场关键身份  → “欢迎【用户名】进入直播间”                  event_id=0                   event_num=身份
danmaku  = 3  # 监听弹幕关键词    → “【用户名】说【内容】”                       event_id=1                   event_num=见弹幕设置
emoticon = 1  # 监听表情包关键词  → “【用户名】说【表情】”                       event_id=2                   event_num=见表情包设置
sc       = 1  # 监听醒目留言     → “【用户名】发送【价格】说【内容】”            event_id=3                    event_num=min(sc价格, 100)/100 # 30元sc为 30/100 = 0.3
guard    = 1  # 监听大航海       → “【用户名】开通【数量】个月【大航海等级】”     event_id=大航海id             event_num=min(舰长月数, 100)/100 # 12月舰长为 12/100 = 0.12
gift     = 3  # 监听礼物         → “【用户名】赠送【数量】个【礼物名】”          event_id=礼物id               event_num=min(礼物数量, 100)/100 # 100个礼物为 100/100 = 1
warning  = 1  # 监听超管警告     → “警告：【警告信息】”                         event_id=警告id              event_num=0

[enter] # 进场
# ============================
# 以下设置为1的身份进场会触发
# ============================
enter_level         = [1, 1, 1, 1, 1] # 身份等级分别对应 【路人，粉丝，舰长，提督，总督】
min_display_time    = [0, 0, 1, 1, 1] # 最短展示秒数分别对应 【路人，粉丝，舰长，提督，总督】

[animation_accumulate] # 动画
# ============================
# 触发以下事件会被累积，每animation_time时间最多处理100,每种需要独占的一个参数：
# 命名为 {来源}_{名称} 比如 guard_提督， 测试时可以直接在弹幕中发送 guard_提督
# 数值 = min(礼物数量, 100)/100 # 10个礼物为 10/100 = 0.1
# 每个礼物应有独立的fx layer，动画由 animation_名字 控制，长度为 animation_time_名字 秒
# osc 每 animation_time 秒汇报一次 animation_名字， 累积为0时汇报 0
# 超出 100 的数量会被拆成多次 100，期间有新礼物会累积
# ============================
animation = ["gift_小花花","gift_牛哇牛哇", "gift_情书"]
animated_parameter = ["flower", "cow", "heart"] # 角色需要有这些参数, ！ASCII限定！
animation_time = [1, 1, 5] # 汇报时间间隔
animation_max_per_time = [100, 100, 1] # 每单位时间最大汇报量，需要小于 100

[set_parameter] # 变化
# ============================
# 触发以下事件时会更新{值名字=[起始值，每次变化值，变大关键词,变小关键词]}最低为0，最高为100
# ============================
parameter_names = ["bust","HairColor"] # 角色需要有“bust”“HairColor”参数
parameter_default = [50, 0] # 起始值为50
parameter_increment = [25, 25] # 每次变化1
parameter_decay_step = [0, 0] # 每次向起始值衰退的值
parameter_decay_time = [30, 30] # 每 x 秒向起始值衰退
parameter_keywords = ["gift_粉丝团灯牌","gift_人气票", "gift_口水黄豆","gift_这个好耶"] # 增加关键词，减少关键词, 每2个对应1个参数

[filter_keywords] # 过滤
# ============================
# 弹幕及表情包关键词设置, event_num 为【在列表中的位置/100】（从1开始数）
# chatbox留空为任意词都触发, event_num = 0
# 长度最多为100
# ============================
danmaku_chatbox_keywords = []
danmaku_parameter_keywords = ["#测试小花花"]
emoticon_chatbox_keywords = []
emoticon_parameter_keywords = ["emoticon_打Call","emoticon_求婚"] # "求婚" event_num 为 2/100 = 0.2


[misc] # 其它
sc_min_display_time = 5 # sc 在聊天框最少显示秒数
guard_min_display_time = 5 # 舰长 在聊天框最少显示秒数
warning_min_display_time = 5 # 警告 在聊天框最少显示秒数